### ISSUE TITLE
VibrantLinux slider missing

### ISSUE THREAD

**Issue by GottaSlay** [zee-mzha/vibrantLinux#15]
[https://i.imgur.com/qNHoaCr.png](url)

I installed by using this method: 
`git clone https://gitlab.com/zee220/vibrantlinux ~/vibrantlinux
`
`cd ~/vibrantlinux`
`./update.sh`

I'm using an RX5700 on Manjaro GNOME. To run the program I dragged and dropped the vibrantLinux file into terminal which output is this: 
`qt5ct: using qt5ct plugin
qt5ct: D-Bus system tray: yes
qt5ct: D-Bus global menu: no
`

**Comment by Scrumplex** [comment]
Try installing it from the AUR instead.

The package you are looking for is vibrantlinux

**Comment by GottaSlay** [comment]
I installed it from AUR and attempted to run it using a desktop icon which didn't do anything? So I tried to run it using terminal instead and got the output: 

`qt5ct: using qt5ct plugin`
`qt5ct: D-Bus system tray: yes`
`Segmentation fault (core dumped)
`
It's not running. On a previous Manjaro installation, I used the separate vibrantlinux-amd build but it doesn't work anymore.

**Comment by Scrumplex** [comment]
can you try with libvibrant-git installed instead of libvibrant?

**Comment by Scrumplex** [comment]
Scrap that. Just update libvibrant to 1.0.1.

**Comment by GottaSlay** [comment]
1.0.1 works, thanks!

**Comment by Scrumplex** [comment]
(psst. you can close the issue now) :wink:
