### ISSUE TITLE
Can't use the program

### ISSUE THREAD

**Issue by tanjilk** [zee-mzha/vibrantLinux#26]
Hey, i cloned the repository with `git clone https://gitlab.com/zee220/vibrantlinux ~/vibrantlinux`
When i run with with `➜  vibrantlinux git:(master) ./update.sh`  :
```
HEAD is now at aca4d37 Update README.md
warning: redirecting to https://gitlab.com/zee220/vibrantlinux.git/
Already up to date.
./update.sh: 15: qmake: not found
make: *** No targets specified and no makefile found.  Stop.
rm: cannot remove '*.o': No such file or directory
rm: cannot remove '*.h': No such file or directory
rm: cannot remove '*.cpp': No such file or directory
rm: cannot remove 'Makefile': No such file or directory
```

I would like to set vibrance in csgo

**Comment by zee-mzha** [comment]
you dont have qmake/qt development files and programs. Please go through the requirements and other steps on the README before opening an issue
