### ISSUE TITLE
vibrantLinux-AMD merge

### ISSUE THREAD

**Issue by TheEvilSkeleton** [zee-mzha/vibrantLinux#3]
Seems like the only [fork](https://github.com/Scrumplex/vibrantLinux-AMD) got AMD GPUs working.

**Comment by Scrumplex** [comment]
Yes! Currently, trying to merge my changes into upstream would break NVIDIA support, as I replaced the NVIDIA-related code. After some more work this can and should be merged upstream.

**Comment by zee-mzha** [comment]
Thank you for creating this issue, Scrumplex is right merging right now would break NVIDIA support. I'll be pushing an update soon that will switch from using nvidia-settings to using libXNVCtrl directly, and along side it I'll be separating the Nvidia logic into its own file that ways it not intermixed with the programs logic. After that update is pushed it should be significantly easier to merge the two.

**Comment by zee-mzha** [comment]
side note: this issue will stay open. Any discussion about how the merge will occur and when it will occur will happen here.

**Comment by Scrumplex** [comment]
Just as an update. AMD support has been merged int the V2 branch of Vibrant Linux. See #5

**Comment by zee-mzha** [comment]
yup closing this issue for now. branch v2 will be merged into the master branch in a few days tops.

**Comment by TheEvilSkeleton** [comment]
> Just as an update. AMD support has been merged int the V2 branch of Vibrant Linux. See #5

Thank you for the update
