### ISSUE TITLE
update.sh: /usr/bin/ld: cannot find -lvibrant

### ISSUE THREAD

**Issue by roiqzt** [zee-mzha/vibrantLinux#32]
What could be the issue? I don't know from which file I should output that library.

**Comment by Scrumplex** [comment]
You need to build and install  [libvibrant](https://github.com/Vibrance-org/libvibrant-legacy)

**Comment by roiqzt** [comment]
> You need to build and install [libvibrant](https://github.com/Vibrance-org/libvibrant-legacy)

What library has to be in `/usr/lib`?

**Comment by Scrumplex** [comment]
You will also need the headers at `/usr/include/vibrant/`

These are all the files you need:
```
/usr/include/vibrant/ctm.h
/usr/include/vibrant/nvidia.h
/usr/include/vibrant/vibrant.h
/usr/lib/libvibrant.so
/usr/lib/libvibrant.so.1
/usr/lib/libvibrant.so.1.0.2
```

**Comment by roiqzt** [comment]
> You will also need the headers at `/usr/include/vibrant/`
> 
> These are all the files you need:
> 
> ```
> /usr/include/vibrant/ctm.h
> /usr/include/vibrant/nvidia.h
> /usr/include/vibrant/vibrant.h
> /usr/lib/libvibrant.so
> /usr/lib/libvibrant.so.1
> /usr/lib/libvibrant.so.1.0.2
> ```

Okay, coping `libvibrant*` into `/usr/lib` solve my problem. Also I don't think we need `ctm.h` or `nvidia.h` inside `/usr/include/vibrant` cause I has only `vibrant.h` there and the program works fine. Thanks
